server:
  port: 8091
spring:
  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    hostname: 192.168.1.41
#    instance-id: ${eureka.instance.hostname}:${server.port}

#ribbon:
#  okhttp:
#    enabled: true
#  restclient:
#    enabled: true

#info:
#  app.name: yxf-microservicecloud
#  company.name: www.wxsstudy.online
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$