# 应用名称
spring:
  application:
    name: spring-cloud-eureka
server:
  port: 8761
  instance:
    hostname: localhost

eureka:
  client:
    service-url:
      defaultZone: http://${server.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: false   #false表示不向注册中心注册自己。